# Generated by Django 3.2.7 on 2021-11-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_avatar_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='avatar',
            new_name='image',
        ),
    ]
